#!/usr/bin/env node

var launch = require('launchpad')
  , static = require('node-static')
  , directory = './public'
  , port = 8000
  , url = 'http://localhost:' + port + '/'

// Create a node-static server instance to serve the './public' folder
var file = new static.Server(directory)
require('http').createServer(function (request, response) {
  request.addListener('end', function () {
    file.serve(request, response)
  }).resume()
}).listen(port)
console.log('Server listening on port', port)

// Try to launch a local browser
launch.local(function(err, local) {
  if (err) {
    console.error('error launching browser: ' + err)
    console.log('open a web browser at ' + url)
    return
  }
  var browsers = local.browsers
    , chrome = false
    , safari = false
    , firefox = false
  if (typeof browsers === null || browsers.length <= 0) {
    console.warn('No browsers found; get chrome: http://chrome.com')
    console.log('Open a web browser at ' + url)
    return
  }
  for (var i = 0 ; i < browsers.length; i++) {
    if (browsers[i].browser === 'chrome') chrome = true
    if (browsers[i].browser === 'safari') safari = true
    if (browsers[i].browser === 'firefox') firefox = true
  }
  if (safari) {
      console.log('Launching safari')
      local.safari(url, function(err, instance) {
        if (err) console.error('unable to launch safari: ' + err)
      })
    }
  else if (chrome) {
    console.log('Launching chrome')
    local.chrome(url, function(err, instance) {
      if (err) console.error('unable to launch chrome: ' + err)
    })
  }
  else if (firefox) {
    console.log('Launching firefox')
    local.firefox(url, function(err, instance) {
      if (err) console.error('unable to launch firefox: ' + err)
    })
  }
  else {
    console.warn('No appropriate browsers found; get chrome: http://chrome.com')
    console.log('Open a web browser at ' + url)
  }
})
